version: '2.2'
services:
  es-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-beta1
    container_name: es-node1
    environment:
      - xpack.security.enabled=false
      - cluster.name=es-cluster
      - node.name=es-node1
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - es-net
  es-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-beta1
    container_name: es-node2
    environment:
      - xpack.security.enabled=false
      - cluster.name=es-cluster
      - node.name=es-node2
      - discovery.seed_hosts=es-node1,es-node2
      - cluster.initial_master_nodes=es-node1,es-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data2:/usr/share/es/data
    networks:
      - es-net
  es-dashboards:
    image: docker.elastic.co/kibana/kibana:8.0.0-beta1
    container_name: es-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://es-node1:9200","http://es-node2:9200"]'
    networks:
      - es-net

volumes:
  es-data1:
  es-data2:

networks:
  es-net:
